from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from uuid import uuid4


class User(AbstractUser):
    """
    Custom user model.
    Overrides base Django user model for custom needs.
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid4,
        help_text=_('ID generated by the system'),
        editable=False
    )
