# Generated by Django 5.0.6 on 2025-03-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, "Didn't respond")], default=2, help_text='Is attending?'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email', max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nickname', max_length=16),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone', max_length=16),
        ),
    ]
