# Generated by Django 5.0.6 on 2025-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_attending_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='age_group',
            field=models.IntegerField(choices=[(0, 'Child'), (1, 'Teenager'), (2, 'Young adult'), (3, 'Adult'), (4, 'Elder')], default=3, help_text='Age group'),
        ),
        migrations.AddField(
            model_name='guest',
            name='attending_probability',
            field=models.FloatField(choices=[(0.0, '0%'), (0.1, '10%'), (0.2, '20%'), (0.3, '30%'), (0.4, '40%'), (0.5, '50%'), (0.6, '60%'), (0.7, '70%'), (0.8, '80%'), (0.9, '90%'), (1.0, '100%')], default=0.0, help_text='Probability of attending'),
        ),
        migrations.AddField(
            model_name='guest',
            name='info',
            field=models.TextField(blank=True, default='', help_text='Relevant notes about the guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='invited_by',
            field=models.IntegerField(choices=[(0, 'Bride'), (1, 'Groom'), (2, 'Both')], default=2, help_text='Who invited the guest'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_vegan',
            field=models.BooleanField(default=False, help_text='Is vegan'),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Is vegetarian'),
        ),
        migrations.AddField(
            model_name='guest',
            name='open_bar',
            field=models.BooleanField(default=True, help_text='Will attend to the open bar'),
        ),
        migrations.AddField(
            model_name='guest',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Friend'), (1, 'Family'), (2, 'Colleague'), (3, 'Other')], default=3, help_text='Relationship with the couple'),
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('first_name', 'last_name')},
        ),
    ]
