# Generated by Django 5.0.6 on 2025-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guest_created_at_alter_guest_other_allergies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='common_allergies',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='is_vegetarian',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='other_allergies',
        ),
        migrations.AddField(
            model_name='guest',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Other allergies'),
        ),
        migrations.AddField(
            model_name='guest',
            name='special_diet',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('child_food', 'Child food'), ('pregnant', 'Pregnant')], default='', max_length=16, verbose_name='Special diet'),
        ),
    ]
