# Generated by Django 5.0.6 on 2025-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_guest_pre_wedding_alter_guest_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='needs_accommodation',
            field=models.BooleanField(default=False, verbose_name='Needs accomodation'),
        ),
        migrations.AddField(
            model_name='guest',
            name='needs_transport',
            field=models.BooleanField(default=False, verbose_name='Needs transport'),
        ),
    ]
