# Generated by Django 5.0.6 on 2025-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_info', '0002_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='include_moodboard',
            field=models.BooleanField(default=False, help_text='Include the moodboard in this FAQ', verbose_name='Include moodboard'),
        ),
    ]
