# Generated by Django 5.0.6 on 2025-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_info', '0003_faq_include_moodboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='include_accommodation',
            field=models.BooleanField(default=False, help_text='Include the accommodation in this FAQ', verbose_name='Include accommodation'),
        ),
    ]
