# Generated by Django 5.0.6 on 2025-03-23 14:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_guest_age_group_guest_attending_probability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='common_allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('gluten', 'Gluten'), ('lactose', 'Lactose'), ('nuts', 'Nuts'), ('seafood', 'Seafood'), ('soy', 'Soy'), ('sugar', 'Sugar')], max_length=8, verbose_name='Common allergies'), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='guest',
            name='other_allergies',
            field=models.TextField(blank=True, default='', verbose_name='Other allergies'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age_group',
            field=models.IntegerField(choices=[(0, 'Child'), (1, 'Teenager'), (2, 'Young adult'), (3, 'Adult'), (4, 'Elder')], default=3, verbose_name='Age group'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, "Didn't respond")], default=2, verbose_name='Is attending?'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending_probability',
            field=models.FloatField(choices=[(0.0, '0%'), (0.1, '10%'), (0.2, '20%'), (0.3, '30%'), (0.4, '40%'), (0.5, '50%'), (0.6, '60%'), (0.7, '70%'), (0.8, '80%'), (0.9, '90%'), (1.0, '100%')], default=0.0, verbose_name='Probability of attending'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.CharField(max_length=32, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Guest group, if any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='guests.guestgroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_by',
            field=models.IntegerField(choices=[(0, 'Bride'), (1, 'Groom'), (2, 'Both')], default=2, help_text='Who invited the guest', verbose_name='Invited by'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Is vegan'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Is vegetarian'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.CharField(max_length=32, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='open_bar',
            field=models.BooleanField(default=True, help_text='Will attend to the open bar', verbose_name='Open bar'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='relationship',
            field=models.IntegerField(choices=[(0, 'Friend'), (1, 'Family'), (2, 'Colleague'), (3, 'Other')], default=3, help_text='Relationship with the couple', verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='guestgroup',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Group name'),
        ),
    ]
